// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXuwZoYVVSofWuIAnJkS9veMge0UtFmU',
    appId: '1:1024537956024:web:6ad0b8032e38bec7d46e4d',
    messagingSenderId: '1024537956024',
    projectId: 'learn-flutter-firebase-7ac86',
    authDomain: 'learn-flutter-firebase-7ac86.firebaseapp.com',
    storageBucket: 'learn-flutter-firebase-7ac86.appspot.com',
    measurementId: 'G-1NX59L8CBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMzkgDx7W1oxZnRUalQSTpXx-mycor7QU',
    appId: '1:1024537956024:android:5f480c921843f34cd46e4d',
    messagingSenderId: '1024537956024',
    projectId: 'learn-flutter-firebase-7ac86',
    storageBucket: 'learn-flutter-firebase-7ac86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR8q6rsYkSN9rDPB9uaQPnVZDmGtZpjGk',
    appId: '1:1024537956024:ios:d48e832f592ef2a2d46e4d',
    messagingSenderId: '1024537956024',
    projectId: 'learn-flutter-firebase-7ac86',
    storageBucket: 'learn-flutter-firebase-7ac86.appspot.com',
    iosBundleId: 'com.example.learnFlutterFirebse',
  );
}
